language: php
php:
  - 5.6
  - 5.5
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php:
      - nightly
      - hhvm
services:
  - memcached
  - redis
install:
  # Extensions install
  - sudo apt-get install php-pear
  - bash install-apcu
  - phpenv config-add travis/$TRAVIS_PHP_VERSION.ini
  - phpenv config-add travis/apc.ini
  # Install deps
  - composer install --dev
  # Get fresh tests
  - rm -rf vendor/maslosoft/cachetest
  - git clone https://github.com/Maslosoft/CacheTest.git vendor/maslosoft/cachetest
  # Ensure that test script is executable
  - chmod +x run-travis
before_script:
# Extensions enable
  - printf "extension=apc.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - printf "extension=apcu.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - printf "extension=memcached.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - printf "extension=redis.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
# Extensions config
  - printf "apc.enable_cli = 1\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - printf "apc.enabled = 1\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - bash run-travis
